### PR TITLE
add travis.

### PR DESCRIPTION
**Pull request by morvencao**
Fix: #23

### CODE REVIEW

**Comment by jichenjc** [comment]
is this still WIP or ready to go?

**Comment by morvencao** [comment]
@jichenjc Still working. Sorry for the late action, I was on business travel and didn't get much time on this.

**Comment by jichenjc** [comment]
no worry and no hurry, I saw some push and I only want to double check whether because you forgot to remove WIP :)

**Comment by morvencao** [comment]
@gyliu513 @jichenjc Seems that we need to enable travis for this original repo, not my forked one before it can verify my PR.

**Comment by gyliu513** [comment]
Thanks @morvencao , I have some trouble to set up travis under ORG `multicloudlab`, let me check this.

**Comment by jichenjc** [comment]
should we reopen this ? I think this is finished? need additional work?

**Comment by gyliu513** [comment]
@jichenjc #23 was opened, let me check more for this.

**Pull request merged**
